### ISSUE TITLE
No longer work woth Typedoc version 0.24+

### ISSUE THREAD

**Issue by karol-f** [luizstacio/typedoc-monorepo-link-types#2]
No longer work with Typedoc version 0.24+ due to error 
```
TypeError: type.getSymbol is not a function
```

It's most likely due to "Removed internal ReferenceType.getSymbol, reference types no longer reference the ts.Symbol to enable generation from serialized JSON." - https://typedoc.org/guides/changelog/#v0.24.0-(2023-04-08)
